### ISSUE TITLE
Implement paste in browser

### ISSUE THREAD

**Issue by bradgrantham** [lkesteloot/trs80-emulator#4]
So I can copy and paste https://www.facebook.com/story.php?story_fbid=10157953582457370&id=780707369

**Comment by bradgrantham** [comment]
Well, that's not a good example; it doesn't appear to be a TRS-80 MODEL 1/2/3 BASIC or even MBASIC program and seems to have lost all its whitespace.

**Comment by lkesteloot** [comment]
That program has a `^` character in it, which wasn't a key on the Model III. Also the initial comment has built-in newlines. I've seen that in programs but I don't know how they entered it. And in any case it wouldn't paste properly.
